 export const ActionTypes={
    GET_USER : "GET_USER",
    GET_AUTH_USER : "GET_AUTH_USER",
    GET_ALL_USER : "GET_ALL_USER",
    CREATE_USER : "CREATE_USER",
    GET_EVENT : "GET_EVENT",
    GET_ALL_EVENTS : "GET_ALL_EVENTS",
    CREATE_EVENT : "CREATE_EVENT",
    GET_EVENT_TYPES : "GET_EVENT_TYPES",
    GET_ALL_EVENT_TYPES : "GET_ALL_EVENT_TYPES",
    CREATE_EVENT_TYPE : "CREATE_EVENT_TYPE",
}